place some other random persons code in the compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,31 +1,111 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
+# fail fast
+set -e
+
+# debug
+# set -x
+
+# parse and derive params
 BUILD_DIR=$1
 CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
-echo "-----> Installing ALPR"
+function error() {
+  echo " !     $*" >&2
+  exit 1
+}
 
-cd $BUILD_DIR
+function topic() {
+  echo "-----> $*"
+}
 
-echo "-----> \tcloning repo..."
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
 
-git clone https://github.com/openalpr/openalpr.git
 
-# Setup the build directory
-echo "-----> \tsetting up build dir..."
-cd openalpr/src
-mkdir build
-cd build
+APT_CACHE_DIR="$CACHE_DIR/apt/cache"
+APT_STATE_DIR="$CACHE_DIR/apt/state"
 
-# setup the compile environment
-echo "-----> \tsetup compile env"
-cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc ..
+mkdir -p "$APT_CACHE_DIR/archives/partial"
+mkdir -p "$APT_STATE_DIR/lists/partial"
 
-# compile the library
-echo "-----> \tcompile lib"
-make
 
-# Install the binaries/libraries to your local system (prefix is /usr)
-echo "-----> \tinstall binaries"
-sudo make install
+APT_OPTIONS="-o debug::nolocking=true -o Dir::Cache::Archives=$APT_CACHE_DIR/archives -o dir::state=$APT_STATE_DIR"
+
+ALPR_REPO="$APT_CACHE_DIR/openalpr.list"
+
+cat /dev/null > $ALPR_REPO
+echo "deb http://archive.ubuntu.com/ubuntu lucid main" >> $ALPR_REPO
+echo "deb http://archive.ubuntu.com/ubuntu lucid-security main" >> $ALPR_REPO
+echo "deb http://archive.ubuntu.com/ubuntu lucid-updates main" >> $ALPR_REPO
+echo "deb http://archive.ubuntu.com/ubuntu lucid universe" >> $ALPR_REPO
+echo "deb http://apt.postgresql.org/pub/repos/apt/ lucid-pgdg 9.2" >> $ALPR_REPO
+echo "deb http://deb.openalpr.com/master/ openalpr main" >> $ALPR_REPO
+
+echo "SOURCE REPO"
+cat $ALPR_REPO
+echo "----------------"
+
+
+APT_OPTIONS="$APT_OPTIONS -o Dir::Etc::SourceList=$ALPR_REPO --allow-unauthenticated"
+
+
+topic "Updating apt caches"
+apt-get $APT_OPTIONS update | indent
+
+for PACKAGE in $(cat $BUILD_DIR/Aptfile); do
+  if [[ $PACKAGE == *deb ]]; then
+    PACKAGE_NAME=$(basename $PACKAGE .deb)
+    PACKAGE_FILE=$APT_CACHE_DIR/archives/$PACKAGE_NAME.deb
+
+    topic "Fetching $PACKAGE"
+    curl -s -L -z $PACKAGE_FILE -o $PACKAGE_FILE $PACKAGE 2>&1 | indent
+  else
+    topic "Fetching .debs for $PACKAGE"
+    echo "apt-get $APT_OPTIONS -y --force-yes download $PACKAGE"
+    apt-get $APT_OPTIONS -y --force-yes download $PACKAGE | indent
+    ls -l $APT_CACHE_DIR/archives
+  fi
+done
+
+echo "debs downloaded"
+ls -lR $CACHE_DIR/apt
+echo "||||||||||||||"
+
+mkdir -p $BUILD_DIR/.apt
+
+for DEB in $(ls -1 $APT_CACHE_DIR/archives/*.deb); do
+  topic "Installing $(basename $DEB)"
+  dpkg -x $DEB $BUILD_DIR/.apt/
+done
+
+topic "Writing profile script"
+mkdir -p $BUILD_DIR/.profile.d
+cat <<EOF >$BUILD_DIR/.profile.d/000_apt.sh
+export PATH="\$HOME/.apt/usr/bin:\$PATH"
+export LD_LIBRARY_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/lib/i386-linux-gnu:\$HOME/.apt/usr/lib:\$LD_LIBRARY_PATH"
+export LIBRARY_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/lib/i386-linux-gnu:\$HOME/.apt/usr/lib:\$LIBRARY_PATH"
+export INCLUDE_PATH="\$HOME/.apt/usr/include:\$INCLUDE_PATH"
+export CPATH="\$INCLUDE_PATH"
+export CPPPATH="\$INCLUDE_PATH"
+export PKG_CONFIG_PATH="\$HOME/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:\$HOME/.apt/usr/lib/i386-linux-gnu/pkgconfig:\$HOME/.apt/usr/lib/pkgconfig:\$PKG_CONFIG_PATH"
+EOF
+
+export PATH="$BUILD_DIR/.apt/usr/bin:$PATH"
+export LD_LIBRARY_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu:$BUILD_DIR/.apt/usr/lib:$LD_LIBRARY_PATH"
+export LIBRARY_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu:$BUILD_DIR/.apt/usr/lib:$LIBRARY_PATH"
+export INCLUDE_PATH="$BUILD_DIR/.apt/usr/include:$INCLUDE_PATH"
+export CPATH="$INCLUDE_PATH"
+export CPPPATH="$INCLUDE_PATH"
+export PKG_CONFIG_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu/pkgconfig:$BUILD_DIR/.apt/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
+
+#give environment to later buildpacks
+export | grep -E -e ' (PATH|LD_LIBRARY_PATH|LIBRARY_PATH|INCLUDE_PATH|CPATH|CPPPATH|PKG_CONFIG_PATH)='  > "$LP_DIR/export"
+exit 1
